name: Spell Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run spell check
        run:  git diff --name-only | npx cspell --file-list stdin
